export default {
  container: {
    display: 'flex',
    flexDirection: 'row',
    position: 'relative',
    overflow: 'hidden',
    height: 48,
  },
  tabContainer: {
    display: 'flex',
    flexDirection: 'row',
    position: 'absolute',
    left: 0,
    transition: 'all 300ms ease',
  },
  linkContainer: {
    display: 'flex',
    minWidth: 100,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 24,
    paddingRight: 24,
    color: '#ffffff',
    textDecoration: 'none',
    fontSize: 14,
  },
  pageLeft: {
    cursor: 'pointer',
    position: 'absolute',
    left: 0,
    color: '#ffffff',
    fontSize: 17,
    padding: 15,
  },
  pageRight: {
    cursor: 'pointer',
    position: 'absolute',
    top: 0,
    right: 0,
    color: '#ffffff',
    fontSize: 17,
    padding: 15,
  },
  activeBar: {
    position: 'absolute',
    bottom: 0,
    height: 3,
    backgroundColor: '#ffffff',
    transition: 'all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms',
  },
};
